base: &base
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *base
  database: ingress_development

test:
  <<: *base
  database: ingress_test
